### ISSUE TITLE
Asking for Designing Logo

### ISSUE THREAD

**Issue by itzmeanjan** [itzmeanjan/transferZ#1]
I'd like to request designers out there to make a logo for this opensource project.

@Tobaloidee could you take a look at it ?

Thanks :heart:

**Comment by Tobaloidee** [comment]
Surely I will! 👍😀

**Comment by Tobaloidee** [comment]
Here's what I came up with for transferZ @itzmeanjan  I hope you like it!

- made a logo design in unison with your mapZ logo design. I incorporated the Z silhouette with the Transfer & File/Folder symbols to make it meaningful and unique. Simple, Minimal, Strong and Memorable.

*the colors applied was based from transferZ github images

![fin-01](https://user-images.githubusercontent.com/36028424/56609414-a0e75a00-663f-11e9-924b-187b40646889.png)

![read](https://user-images.githubusercontent.com/36028424/56609420-a47ae100-663f-11e9-9cf5-2c68da62307b.png)

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee , I do like your color choice in two arrows, which are similar as I used in app UI. 

Good work :+1:

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee ,

As this is an Android App built with :heart: using Flutter, I'd like to request you to design icons for this app. 

Icons generally reside within this [directory](https://github.com/itzmeanjan/transferZ/tree/master/android/app/src/main/res), for an android app. 

I think your current design will be good for icon, just you need to make different icons with different resolution, for supporting various screen sizes. 

Please submit a PR when you're done with that :wink: .

**Comment by Tobaloidee** [comment]
Surely! I will finalize the files and icons in different resolutions

**Comment by Tobaloidee** [comment]
Here's the PR #2 with the icons & logo upload and Readme Update @itzmeanjan.

Also, you can download all the versions and formats of the new logo [HERE](https://drive.google.com/drive/u/0/folders/1XcLAOo_G4qck8PjsZbjh0KvVgWKxXDk4)

Thanks a lot! Will check your other project again for logos :)

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee , have merged with master branch.

Thanks again :+1: and contributions are always welcome :wink:
