### ISSUE TITLE
How to use the app?

### ISSUE THREAD

**Issue by g7i** [itzmeanjan/transferZ#3]
I am unable to use the app. When clicking on the send or receive icon, the progress indicator goes on endlessly. Is there anything needed to done?

**Comment by Rawlin-cypher** [comment]
both the devices should be on the same wifi network, use a third device as a wifi and connect other two devices to the wifi.

**Comment by itzmeanjan** [comment]
Hello @GouravSaini125 , make sure your participating devices are present within same network. So connect them to same Wifi.

**Comment by Shrulabh** [comment]
I am facing the same issue as @GouravSaini125 , the two devices are connected to the same wifi network,
On clicking the icons the progress loader goes on endlessly.

**Comment by itzmeanjan** [comment]
Please note that, your router must have UDP multicasting enabled, due to the fact, `transferZ` will leverage that functionality to discover its peers in certain network.

cc @Shrulabh @GouravSaini125

**Comment by shiiijo** [comment]
when I try to send files , application is closing completely by itself @itzmeanjan , @Gourav Saini  can you help me with this
